<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TagSelecta.Shared\TagSelecta.Shared.csproj" />
    <ProjectReference Include="..\TagSelecta.TagDataActions.Abstractions\TagSelecta.TagDataActions.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>
</Project>
