<?xml version="1.0"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TagSelecta.Tagging\TagSelecta.Tagging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="1.0.0-alpha.0.12" />
  </ItemGroup>
</Project>
