Output demo.mp4
Set FontFamily "JetBrainsMono Nerd Font"
Set FontSize 18
Set Theme "GitHub Dark"
Set Padding 10
Set Width 1000
Set Height 800
Set Shell bash

Type './tagselecta e ./Album'
Enter
Sleep 2s
Type j
Sleep 2s
Type j
Sleep 2s
Type j
Sleep 5s
Type q

Type './tagselecta e ./Album -g "Reggae; Dub" -N 5 -y 2024 -s "URL=https://cantti.bandcamp.com"'
Enter
Sleep 2s
Type j
Sleep 2s
Type j
Sleep 2s
Type j
Sleep 2s
Type w
Sleep 5s
Type q

Type './tagselecta discogs ./Album -r https://www.discogs.com/master/186940-King-Tubby-Dub-From-The-Roots'
Enter
Sleep 10s
Type q
